# Generated by Django 3.2.7 on 2021-09-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('names', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('last_name_1', models.CharField(blank=True, max_length=50)),
                ('last_name_2', models.CharField(blank=True, max_length=50)),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee_number', models.IntegerField(blank=True, null=True)),
                ('employee_title', models.CharField(blank=True, max_length=50)),
                ('number_jefe', models.IntegerField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, max_length=10)),
                ('municipio', models.CharField(blank=True, max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=50)),
                ('ventas_2019', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, max_length=200, null=True, upload_to='pictures', verbose_name='Imagen de Perfil')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
